// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzeziuXgWLsN428FtOD0Ry5PLxeI5civM',
    appId: '1:654907094747:web:ecbe97b19260c4a640fefe',
    messagingSenderId: '654907094747',
    projectId: 'eco-estimasi-service',
    authDomain: 'eco-estimasi-service.firebaseapp.com',
    storageBucket: 'eco-estimasi-service.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb13ZahX_UeO4A9g0pmlDbTHnPkeAh3vg',
    appId: '1:654907094747:android:5a583a29ba8ca2ce40fefe',
    messagingSenderId: '654907094747',
    projectId: 'eco-estimasi-service',
    storageBucket: 'eco-estimasi-service.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx7bN2sAcv1HtFnmyFYZbTU6b54y2fWtM',
    appId: '1:654907094747:ios:0d90c955617780a040fefe',
    messagingSenderId: '654907094747',
    projectId: 'eco-estimasi-service',
    storageBucket: 'eco-estimasi-service.firebasestorage.app',
    iosBundleId: 'com.example.estimasiService',
  );
}
